version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.favicon
    - babel.html
    - styles/*
    - images/*
    - dist/bundle.js
